// <auto-generated />
using System;
using Hoteldia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoteldia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810153239_SeedCountries")]
    partial class SeedCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoteldia.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hoteldia.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Hoteldia.Modelos.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afganistán"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DE",
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AG",
                            Name = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Code = "SA",
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DZ",
                            Name = "Argelia"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AZ",
                            Name = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BD",
                            Name = "Bangladés"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BH",
                            Name = "Baréin"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BE",
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BZ",
                            Name = "Belice"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BJ",
                            Name = "Benín"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BY",
                            Name = "Bielorrusia"
                        },
                        new
                        {
                            Id = 22,
                            Code = "MM",
                            Name = "Birmania/Myanmar"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BA",
                            Name = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BW",
                            Name = "Botsuana"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BR",
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BN",
                            Name = "Brunéi"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 32,
                            Code = "KH",
                            Name = "Camboya"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CM",
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CA",
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = 35,
                            Code = "QA",
                            Name = "Catar"
                        },
                        new
                        {
                            Id = 36,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CY",
                            Name = "Chipre"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 41,
                            Code = "KM",
                            Name = "Comoras"
                        },
                        new
                        {
                            Id = 42,
                            Code = "KP",
                            Name = "Corea del Norte"
                        },
                        new
                        {
                            Id = 43,
                            Code = "KR",
                            Name = "Corea del Sur"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CI",
                            Name = "Costa de Marfil"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 46,
                            Code = "HR",
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 48,
                            Code = "DK",
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = 49,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 51,
                            Code = "EG",
                            Name = "Egipto"
                        },
                        new
                        {
                            Id = 52,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            Code = "AE",
                            Name = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 54,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            Code = "SK",
                            Name = "Eslovaquia"
                        },
                        new
                        {
                            Id = 56,
                            Code = "SI",
                            Name = "Eslovenia"
                        },
                        new
                        {
                            Id = 57,
                            Code = "ES",
                            Name = "España"
                        },
                        new
                        {
                            Id = 58,
                            Code = "US",
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 59,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 60,
                            Code = "SZ",
                            Name = "Esuatini"
                        },
                        new
                        {
                            Id = 61,
                            Code = "ET",
                            Name = "Etiopía"
                        },
                        new
                        {
                            Id = 62,
                            Code = "PH",
                            Name = "Filipinas"
                        },
                        new
                        {
                            Id = 63,
                            Code = "FI",
                            Name = "Finlandia"
                        },
                        new
                        {
                            Id = 64,
                            Code = "FJ",
                            Name = "Fiyi"
                        },
                        new
                        {
                            Id = 65,
                            Code = "FR",
                            Name = "Francia"
                        },
                        new
                        {
                            Id = 66,
                            Code = "GA",
                            Name = "Gabón"
                        },
                        new
                        {
                            Id = 67,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 69,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 70,
                            Code = "GD",
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 71,
                            Code = "GR",
                            Name = "Grecia"
                        },
                        new
                        {
                            Id = 72,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 73,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 74,
                            Code = "GW",
                            Name = "Guinea-Bisáu"
                        },
                        new
                        {
                            Id = 75,
                            Code = "GQ",
                            Name = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = 76,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 77,
                            Code = "HT",
                            Name = "Haití"
                        },
                        new
                        {
                            Id = 78,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 79,
                            Code = "HU",
                            Name = "Hungría"
                        },
                        new
                        {
                            Id = 80,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 81,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 82,
                            Code = "IQ",
                            Name = "Irak"
                        },
                        new
                        {
                            Id = 83,
                            Code = "IR",
                            Name = "Irán"
                        },
                        new
                        {
                            Id = 84,
                            Code = "IE",
                            Name = "Irlanda"
                        },
                        new
                        {
                            Id = 85,
                            Code = "IS",
                            Name = "Islandia"
                        },
                        new
                        {
                            Id = 86,
                            Code = "MH",
                            Name = "Islas Marshall"
                        },
                        new
                        {
                            Id = 87,
                            Code = "SB",
                            Name = "Islas Salomón"
                        },
                        new
                        {
                            Id = 88,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 89,
                            Code = "IT",
                            Name = "Italia"
                        },
                        new
                        {
                            Id = 90,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 91,
                            Code = "JP",
                            Name = "Japón"
                        },
                        new
                        {
                            Id = 92,
                            Code = "JO",
                            Name = "Jordania"
                        },
                        new
                        {
                            Id = 93,
                            Code = "KZ",
                            Name = "Kazajistán"
                        },
                        new
                        {
                            Id = 94,
                            Code = "KE",
                            Name = "Kenia"
                        },
                        new
                        {
                            Id = 95,
                            Code = "KG",
                            Name = "Kirguistán"
                        },
                        new
                        {
                            Id = 96,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 97,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 98,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 99,
                            Code = "LS",
                            Name = "Lesoto"
                        },
                        new
                        {
                            Id = 100,
                            Code = "LV",
                            Name = "Letonia"
                        },
                        new
                        {
                            Id = 101,
                            Code = "LB",
                            Name = "Líbano"
                        },
                        new
                        {
                            Id = 102,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 103,
                            Code = "LY",
                            Name = "Libia"
                        },
                        new
                        {
                            Id = 104,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 105,
                            Code = "LT",
                            Name = "Lituania"
                        },
                        new
                        {
                            Id = 106,
                            Code = "LU",
                            Name = "Luxemburgo"
                        },
                        new
                        {
                            Id = 107,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 108,
                            Code = "MY",
                            Name = "Malasia"
                        },
                        new
                        {
                            Id = 109,
                            Code = "MW",
                            Name = "Malaui"
                        },
                        new
                        {
                            Id = 110,
                            Code = "MV",
                            Name = "Maldivas"
                        },
                        new
                        {
                            Id = 111,
                            Code = "ML",
                            Name = "Malí"
                        },
                        new
                        {
                            Id = 112,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MA",
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MU",
                            Name = "Mauricio"
                        },
                        new
                        {
                            Id = 115,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 116,
                            Code = "MX",
                            Name = "México"
                        },
                        new
                        {
                            Id = 117,
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 118,
                            Code = "MD",
                            Name = "Moldavia"
                        },
                        new
                        {
                            Id = 119,
                            Code = "MC",
                            Name = "Mónaco"
                        },
                        new
                        {
                            Id = 120,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 121,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 122,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 123,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 124,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 125,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 126,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 127,
                            Code = "NE",
                            Name = "Níger"
                        },
                        new
                        {
                            Id = 128,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 129,
                            Code = "NO",
                            Name = "Noruega"
                        },
                        new
                        {
                            Id = 130,
                            Code = "NZ",
                            Name = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 131,
                            Code = "OM",
                            Name = "Omán"
                        },
                        new
                        {
                            Id = 132,
                            Code = "NL",
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = 133,
                            Code = "PK",
                            Name = "Pakistán"
                        },
                        new
                        {
                            Id = 134,
                            Code = "PW",
                            Name = "Palaos"
                        },
                        new
                        {
                            Id = 135,
                            Code = "PA",
                            Name = "Panamá"
                        },
                        new
                        {
                            Id = 136,
                            Code = "PG",
                            Name = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = 137,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 138,
                            Code = "PE",
                            Name = "Perú"
                        },
                        new
                        {
                            Id = 139,
                            Code = "PL",
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = 140,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            Code = "GB",
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Id = 142,
                            Code = "CF",
                            Name = "República Centroafricana"
                        },
                        new
                        {
                            Id = 143,
                            Code = "CZ",
                            Name = "República Checa"
                        },
                        new
                        {
                            Id = 144,
                            Code = "CG",
                            Name = "República del Congo"
                        },
                        new
                        {
                            Id = 145,
                            Code = "CD",
                            Name = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = 146,
                            Code = "DO",
                            Name = "República Dominicana"
                        },
                        new
                        {
                            Id = 147,
                            Code = "RW",
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = 148,
                            Code = "RO",
                            Name = "Rumanía"
                        },
                        new
                        {
                            Id = 149,
                            Code = "RU",
                            Name = "Rusia"
                        },
                        new
                        {
                            Id = 150,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 151,
                            Code = "KN",
                            Name = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = 152,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 153,
                            Code = "VC",
                            Name = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = 154,
                            Code = "LC",
                            Name = "Santa Lucía"
                        },
                        new
                        {
                            Id = 155,
                            Code = "ST",
                            Name = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 156,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 157,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 158,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 159,
                            Code = "SL",
                            Name = "Sierra Leona"
                        },
                        new
                        {
                            Id = 160,
                            Code = "SG",
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 161,
                            Code = "SY",
                            Name = "Siria"
                        },
                        new
                        {
                            Id = 162,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 163,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            Code = "ZA",
                            Name = "Sudáfrica"
                        },
                        new
                        {
                            Id = 165,
                            Code = "SD",
                            Name = "Sudán"
                        },
                        new
                        {
                            Id = 166,
                            Code = "SS",
                            Name = "Sudán del Sur"
                        },
                        new
                        {
                            Id = 167,
                            Code = "SE",
                            Name = "Suecia"
                        },
                        new
                        {
                            Id = 168,
                            Code = "CH",
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = 169,
                            Code = "SR",
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = 170,
                            Code = "TH",
                            Name = "Tailandia"
                        },
                        new
                        {
                            Id = 171,
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            Code = "TJ",
                            Name = "Tayikistán"
                        },
                        new
                        {
                            Id = 173,
                            Code = "TL",
                            Name = "Timor Oriental"
                        },
                        new
                        {
                            Id = 174,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 176,
                            Code = "TT",
                            Name = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = 177,
                            Code = "TN",
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = 178,
                            Code = "TM",
                            Name = "Turkmenistán"
                        },
                        new
                        {
                            Id = 179,
                            Code = "TR",
                            Name = "Turquía"
                        },
                        new
                        {
                            Id = 180,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 181,
                            Code = "UA",
                            Name = "Ucrania"
                        },
                        new
                        {
                            Id = 182,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 183,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 184,
                            Code = "UZ",
                            Name = "Uzbekistán"
                        },
                        new
                        {
                            Id = 185,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 186,
                            Code = "VA",
                            Name = "Vaticano"
                        },
                        new
                        {
                            Id = 187,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 188,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 189,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 190,
                            Code = "DJ",
                            Name = "Yibuti"
                        },
                        new
                        {
                            Id = 191,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 192,
                            Code = "ZW",
                            Name = "Zimbabue"
                        });
                });

            modelBuilder.Entity("Hoteldia.Modelos.ImagenPropiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropiedadId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("ImagenPropiedad");
                });

            modelBuilder.Entity("Hoteldia.Modelos.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int>("Banios")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CountryId");

                    b.ToTable("Propiedad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hoteldia.Modelos.ImagenPropiedad", b =>
                {
                    b.HasOne("Hoteldia.Modelos.Propiedad", "Propiedad")
                        .WithMany("ImagenPropiedad")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Hoteldia.Modelos.Propiedad", b =>
                {
                    b.HasOne("Hoteldia.Modelos.Categoria", "Categoria")
                        .WithMany("Propiedad")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoteldia.Modelos.Country", "Country")
                        .WithMany("Propiedades")
                        .HasForeignKey("CountryId");

                    b.Navigation("Categoria");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hoteldia.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hoteldia.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoteldia.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hoteldia.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hoteldia.Modelos.Categoria", b =>
                {
                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Hoteldia.Modelos.Country", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("Hoteldia.Modelos.Propiedad", b =>
                {
                    b.Navigation("ImagenPropiedad");
                });
#pragma warning restore 612, 618
        }
    }
}
